### PR TITLE
Dev rate factor p schange

### PR DESCRIPTION
**Pull request by pkausw**

### CODE REVIEW

**Comment by sebwieland** [comment]
Do these changes mean, that one automatically considers the change of for example ttlf/cc when varyiing isr ttbb?
Or is it optional?

**Comment by pkausw** [comment]
> Do these changes mean, that one automatically considers the change of for example ttlf/cc when varyiing isr ttbb?
> Or is it optional?

the fractions are read out automatically, but how (or even if) you use them in the first place is configured by the expressions for the respective systematic in the systs.csv

**Comment by sebwieland** [comment]
> > Do these changes mean, that one automatically considers the change of for example ttlf/cc when varyiing isr ttbb?
> > Or is it optional?
> 
> the fractions are read out automatically, but how (or even if) you use them in the first place is configured by the expressions for the respective systematic in the systs.csv

Okay, this makes sense.
My question would then be, if the systs.csv s are already updated concerning this.
Nonetheless, lftm :+1:

**Comment by pkausw** [comment]
> > > Do these changes mean, that one automatically considers the change of for example ttlf/cc when varyiing isr ttbb?
> > > Or is it optional?
> > 
> > 
> > the fractions are read out automatically, but how (or even if) you use them in the first place is configured by the expressions for the respective systematic in the systs.csv
> 
> Okay, this makes sense.
> My question would then be, if the systs.csv s are already updated concerning this.
> Nonetheless, lftm +1

Yes, they are, see commit 887f3b39192c96d93c79ef13b52eb072ad9cb917

**Pull request merged**
