### PR TITLE
update to newer TF version(1.50)

### PR DESCRIPTION
**Pull request by sebwieland**
Requires to Run plotscript on SL7 entirely, which is the future

### CODE REVIEW

**Comment by pkausw** [comment]
Does this mean that the plotscript is now running on CMSSW_10 entirely?

**Comment by sebwieland** [comment]
Yes, although
`export SCRAM_ARCH=slc7_amd64_gcc700`
 `CMSSW_10_6_10`
is a somewhat hard requirement when evaluating DNNs

**Comment by pkausw** [comment]
I propose to make a new git version then

**Comment by sebwieland** [comment]
What do you mean by "new git version"
A new branch? Like RealRealLegacyAnalysis?

**Comment by pkausw** [comment]
> What do you mean by "new git version"
> A new branch? Like RealRealLegacyAnalysis?

Sorry, meant new release :D So then we'd have the current main branch as a release for CMSSW_9_4_6 and this new addition/upgrade as a release for CMSSW_10

Or do you think that's overkill?

**Comment by sebwieland** [comment]
Ah I see.
Hm, I think this would be a little overkill.
I suppose to use CMSSW_10_6_10 on sl7 as default anyhow, since CC7 is the future ;)

**Comment by sebwieland** [comment]
Encountered some Problems with TF Version. PR will not work...
Working on it....

**Pull request closed without merging**
