### PR TITLE
The real legacy analysis naming

### PR DESCRIPTION
**Pull request by pkausw**
changed structure of c++ file and changed code so `internalNormFactors` are properly applied

### CODE REVIEW

**Comment by sebwieland** [comment]
Does this require any modifications int he Frontend, such as the toplevel plottingscript?

**Review by JanvanderLinden — COMMENTED** [review]
Is this compatible with CMSSW 10?
Would be nice to be able to run the plotscript with it in future, as youre already on it ;)
Looks fine otherwise

**Comment by pkausw** [comment]
> Does this require any modifications int he Frontend, such as the toplevel plottingscript?

No, all changes were made in the backend

**Comment by pkausw** [comment]
> Is this compatible with CMSSW 10?
> Would be nice to be able to run the plotscript with it in future, as youre already on it ;)
> Looks fine otherwise

I didn't try it with CMSSW 10, but I can give it a try :D

**Pull request merged**
