### PR TITLE
Implementation of DNN crossevaluation to double the MC statistics during evaluation

### PR DESCRIPTION
**Pull request by JanvanderLinden**
So far, the DNNs were evaluated only on half of the available MC samples with an Odd `Evt_ID`, because the other half (with an Even `Evt_ID`) was used to train the DNNs. 

## Feature

This newly implemented feature allows for an evaluation of multiple DNNs where the DNN outputs are filled in common discriminators.
For example, one can train two DNNs -- one on the `Even` part of the MC samples, one on the `Odd` part of the MC sample -- then evaluate the `Even` part of the MC sample with the DNN trained on the `Odd` part (and vice versa), and subsequently fill the outputs of both DNNs into common discriminators.

## Cross Evaluation Workflow

- first train separate DNNs with the `DRACO_MLfoy` Framework on the `Odd/Even` subsamples by appending the options `--even` or `--odd` to the execution of the train script (this of course requires a previous preprocessing of `Odd` and `Even` MC events)
- generate a new set of DNNs with the following structure:
```
NAME_OF_DNN_SET
----/DNNS_OF_FIRST_JT_REGION
--------/ODD
------------checkpointfiles
--------/EVEN
------------checkpointfiles
----/DNNS_OF_SECOND_JT_REGION
...
```
- generate a new `plt_config` with the `utils/tools/dNNInterfaces/MLfoyInterface.py` and specify the option `-x` to activate the cross evaluation setup.
Activating this option creates input-feature-plots and output-discriminator-plots for each jet-tag-region by combining the subfolders (`EVEN/ODD`). If the option is not specified when creating the new `plt_config`, separate plots are created for the subfolder checkpoint files.
- add the created config to the `plt_config` variable in your top-level-script.
- check your `config` file and remove the `(Evt_Odd==0)*2.0` selection if it still exists and replace it by `1.0` to select all events and remove the adjusted weight.
- add the variable `Evt_Odd` to your `variable_cfg` if it does not exist yet.
- add the option `crossEvaluation` to your `analysisOptions` dictionary in the top-level-script if it does not exist yet and set it to `True`.
If the option is set to `False` the `c++` code that is written will evaluate all DNNs separately, so you also need a `plt_config` that was not created with the `-x` option.
- set the path to your new DNNSet in the `dnnInterface` dictionary in the top-level-script.
- execute the top-level-script as usual.

### CODE REVIEW

**Comment by pkausw** [comment]
Nice feature! It would be really nice to have these instructions in some kind of README (that is not part of a pull request) to make sure that this information doesn't get lost!

**Comment by kelmorab** [comment]
Is this used for all samples?
How do you treat data?

**Comment by JanvanderLinden** [comment]
Dear Mr. El,
thank you for your questions.

> Is this used for all samples?

Yes, this is used for all samples. So in the end you only gain in MC statistics for the samples you used for training (i.e. major background samples), because the other samples didnt have even/odd splitting until now.
> How do you treat data?

A single data event is only evaluated with one of the two even/odd DNNs according to its `Evt_Odd` variable. So you kinda split your data events randomly in half, evaluate them separately and subsequently fill them into the same discriminator.
So no data event splitting/weighting is performed, as it is not allowed!

**Comment by JanvanderLinden** [comment]
> Nice feature! It would be really nice to have these instructions in some kind of README (that is not part of a pull request) to make sure that this information doesn't get lost!

Thank you for your review!
I added the `Cross Evaluation Workflow` section to the `README`.

**Comment by sebwieland** [comment]
Really Nice Feature.
From my side everything is ready to be merged!
Grats Jan!

**Review by sebwieland — APPROVED** [review]

**Pull request merged**
